#include "types.hpp"

#undef ENUM_BEGIN
#undef ENUM_END
#undef ENUM_ITEM
#undef ENUM_ITEM_PAIR
#undef ENUM_OUTPUT_DECL
#define ENUM_BEGIN ENUM_OUTPUT_BEGIN
#define ENUM_END ENUM_OUTPUT_END
#define ENUM_ITEM ENUM_OUTPUT_ITEM
#define ENUM_ITEM_PAIR ENUM_OUTPUT_ITEM_PAIR
#define ENUM_OUTPUT_DECL(E) 

NS_BEGIN_2(odbclib,handle)

ENUM_BEGIN(HandleType)
	ENUM_ITEM_PAIR(Null,0)
	ENUM_ITEM_PAIR(Environment,SQL_HANDLE_ENV)
	ENUM_ITEM_PAIR(Connection,SQL_HANDLE_DBC)
	ENUM_ITEM_PAIR(Statement,SQL_HANDLE_STMT)
	ENUM_ITEM_PAIR(Descriptor,SQL_HANDLE_DESC)
ENUM_END(HandleType)
ENUM_OUTPUT_DECL(HandleType)

NS_END_2

NS_BEGIN_2(odbclib,diagnostics)

ENUM_BEGIN(DiagLevel)
	ENUM_ITEM(Information)
	ENUM_ITEM(Warning)
	ENUM_ITEM(Error)
ENUM_END(DiagLevel)
ENUM_OUTPUT_DECL(DiagLevel)

NS_END_2

NS_BEGIN_2(odbclib,environment)

ENUM_BEGIN(EnvironmentVersion)
	ENUM_ITEM_PAIR(ODBC3,SQL_OV_ODBC3)
	ENUM_ITEM_PAIR(ODBC2,SQL_OV_ODBC2)
ENUM_END(EnvironmentVersion)
ENUM_OUTPUT_DECL(EnvironmentVersion)

NS_END_2

NS_BEGIN_2(odbclib,datatypes)
//according to http://msdn.microsoft.com/en-us/library/ms710150(v=VS.85).aspx

ENUM_BEGIN(OdbcSQLType)
	ENUM_ITEM_PAIR(Unknown,SQL_UNKNOWN_TYPE)
	//ENUM_ITEM_PAIR(Null, SQL_TYPE_NULL)
	ENUM_ITEM_PAIR(Char, SQL_CHAR)
	ENUM_ITEM_PAIR(VarChar, SQL_VARCHAR)
	ENUM_ITEM_PAIR(LongVarChar, SQL_LONGVARCHAR)
	ENUM_ITEM_PAIR(WChar, SQL_WCHAR)
	ENUM_ITEM_PAIR(WVarChar, SQL_WVARCHAR)
	ENUM_ITEM_PAIR(WLongVarChar, SQL_WLONGVARCHAR)
	ENUM_ITEM_PAIR(Decimal, SQL_DECIMAL)
	ENUM_ITEM_PAIR(Numeric, SQL_NUMERIC)
	ENUM_ITEM_PAIR(SmallInt, SQL_SMALLINT)
	ENUM_ITEM_PAIR(Integer, SQL_INTEGER)
	ENUM_ITEM_PAIR(Real, SQL_REAL)
	ENUM_ITEM_PAIR(Float, SQL_FLOAT)
	ENUM_ITEM_PAIR(Double, SQL_DOUBLE)
	ENUM_ITEM_PAIR(Bit, SQL_BIT)
	ENUM_ITEM_PAIR(TinyInt,SQL_TINYINT)
	ENUM_ITEM_PAIR(BigInt,SQL_BIGINT)
	ENUM_ITEM_PAIR(Binary,SQL_BINARY)
	ENUM_ITEM_PAIR(VarBinary, SQL_VARBINARY)
	ENUM_ITEM_PAIR(LongVarBinary, SQL_LONGVARBINARY)
	ENUM_ITEM_PAIR(Date, SQL_TYPE_DATE)
	ENUM_ITEM_PAIR(Time, SQL_TYPE_TIME)
	ENUM_ITEM_PAIR(Timestamp, SQL_TYPE_TIMESTAMP)
	/*
	   no SQL_TYPE_UTCDATETIME,SQL_TYPE_UTCTIME found in header files
	   UTCDateTime = SQL_TYPE_UTCDATETIME,
	   UTCTime = SQL_TYPE_UTCTIME,
	   */
	ENUM_ITEM_PAIR(IntervalMonth, SQL_INTERVAL_MONTH)
	ENUM_ITEM_PAIR(IntervalYear, SQL_INTERVAL_YEAR)
	ENUM_ITEM_PAIR(IntervalYearToMonth, SQL_INTERVAL_YEAR_TO_MONTH)
	ENUM_ITEM_PAIR(IntervalDay, SQL_INTERVAL_DAY)
	ENUM_ITEM_PAIR(IntervalHour, SQL_INTERVAL_HOUR)
	ENUM_ITEM_PAIR(IntervalMinute, SQL_INTERVAL_MINUTE)	
	ENUM_ITEM_PAIR(IntervalSecond, SQL_INTERVAL_SECOND)
	ENUM_ITEM_PAIR(IntervalDayToHour, SQL_INTERVAL_DAY_TO_HOUR)
	ENUM_ITEM_PAIR(IntervalDayToMinute, SQL_INTERVAL_DAY_TO_MINUTE)
	ENUM_ITEM_PAIR(IntervalDayToSecond, SQL_INTERVAL_DAY_TO_SECOND)
	ENUM_ITEM_PAIR(IntervalHourToMinute, SQL_INTERVAL_HOUR_TO_MINUTE)
	ENUM_ITEM_PAIR(IntervalHourToSecond, SQL_INTERVAL_HOUR_TO_SECOND)
	ENUM_ITEM_PAIR(IntervalMinuteToSecond, SQL_INTERVAL_MINUTE_TO_SECOND)
	ENUM_ITEM_PAIR(Guid, SQL_GUID)
ENUM_END(OdbcSQLType)
ENUM_OUTPUT_DECL(OdbcSQLType)

NS_END_2

NS_BEGIN_2(odbclib,ctypes)

//according to http://msdn.microsoft.com/en-us/library/ms714556(v=VS.85).aspx
ENUM_BEGIN(OdbcCType)
	ENUM_ITEM_PAIR(Default, SQL_C_DEFAULT)
	ENUM_ITEM_PAIR(Char, SQL_C_CHAR)
	ENUM_ITEM_PAIR(WChar, SQL_C_WCHAR)
	ENUM_ITEM_PAIR(Short, SQL_C_SHORT)
	ENUM_ITEM_PAIR(SShort, SQL_C_SSHORT)
	ENUM_ITEM_PAIR(UShort, SQL_C_USHORT)
	ENUM_ITEM_PAIR(Long, SQL_C_LONG)
	ENUM_ITEM_PAIR(SLong, SQL_C_SLONG)
	ENUM_ITEM_PAIR(ULong, SQL_C_ULONG)
	ENUM_ITEM_PAIR(Float, SQL_C_FLOAT)
	ENUM_ITEM_PAIR(Double, SQL_C_DOUBLE)
	ENUM_ITEM_PAIR(Bit, SQL_C_BIT)
	ENUM_ITEM_PAIR(TinyInt, SQL_C_TINYINT)
	ENUM_ITEM_PAIR(STinyInt, SQL_C_STINYINT)
	ENUM_ITEM_PAIR(UTinyInt, SQL_C_UTINYINT)
	ENUM_ITEM_PAIR(SBigInt, SQL_C_SBIGINT)
	ENUM_ITEM_PAIR(UBigInt, SQL_C_UBIGINT)
	ENUM_ITEM_PAIR(Binary, SQL_C_BINARY)
	//ENUM_ITEM_PAIR(Bookmark, SQL_C_BOOKMARK)
	//ENUM_ITEM_PAIR(VarBookmark, SQL_C_VARBOOKMARK)
	ENUM_ITEM_PAIR(Date, SQL_C_TYPE_DATE)
	ENUM_ITEM_PAIR(Time, SQL_C_TYPE_TIME)
	ENUM_ITEM_PAIR(Timestamp, SQL_C_TYPE_TIMESTAMP)
	ENUM_ITEM_PAIR(Numeric, SQL_C_NUMERIC)
	ENUM_ITEM_PAIR(Guid, SQL_C_GUID)
	ENUM_ITEM_PAIR(IntervalMonth, SQL_C_INTERVAL_MONTH)
	ENUM_ITEM_PAIR(IntervalYear, SQL_C_INTERVAL_YEAR)
	ENUM_ITEM_PAIR(IntervalYearToMonth, SQL_C_INTERVAL_YEAR_TO_MONTH)
	ENUM_ITEM_PAIR(IntervalDay, SQL_C_INTERVAL_DAY)
	ENUM_ITEM_PAIR(IntervalHour, SQL_C_INTERVAL_HOUR)
	ENUM_ITEM_PAIR(IntervalMinute, SQL_C_INTERVAL_MINUTE)
	ENUM_ITEM_PAIR(IntervalSecond, SQL_C_INTERVAL_SECOND)
	ENUM_ITEM_PAIR(IntervalDayToHour, SQL_C_INTERVAL_DAY_TO_HOUR)
	ENUM_ITEM_PAIR(IntervalDayToMinute, SQL_C_INTERVAL_DAY_TO_MINUTE)
	ENUM_ITEM_PAIR(IntervalDayToSecond, SQL_C_INTERVAL_DAY_TO_SECOND)
	ENUM_ITEM_PAIR(IntervalHourToMinute, SQL_C_INTERVAL_HOUR_TO_MINUTE)
	ENUM_ITEM_PAIR(IntervalHourToSecond, SQL_C_INTERVAL_HOUR_TO_SECOND)
	ENUM_ITEM_PAIR(IntervalMinuteToSecond, SQL_C_INTERVAL_MINUTE_TO_SECOND)
ENUM_END(OdbcCType)
ENUM_OUTPUT_DECL(OdbcCType)

NS_END_2

NS_BEGIN_2(odbclib,fetchtypes)

/*
#define SQL_FETCH_ABSOLUTE 5
#define SQL_FETCH_DIRECTION 8
#define SQL_FETCH_FIRST 2
#define SQL_FETCH_LAST 3
#define SQL_FETCH_NEXT 1
#define SQL_FETCH_PRIOR 4
#define SQL_FETCH_RELATIVE 6
SQL_FETCH_BOOKMARK
 */
ENUM_BEGIN(FetchOrientation)
	ENUM_ITEM_PAIR(Next,SQL_FETCH_NEXT)
	ENUM_ITEM_PAIR(Previous,SQL_FETCH_PRIOR)
	ENUM_ITEM_PAIR(First,SQL_FETCH_FIRST)
	ENUM_ITEM_PAIR(Last,SQL_FETCH_LAST)
	ENUM_ITEM_PAIR(Relative,SQL_FETCH_RELATIVE)
	ENUM_ITEM_PAIR(Absolute,SQL_FETCH_ABSOLUTE)
	ENUM_ITEM_PAIR(Bookmark,SQL_FETCH_BOOKMARK)
ENUM_END(FetchOrientation)
ENUM_OUTPUT_DECL(FetchOrientation)

typedef SQLLEN fetchoffset_t;

NS_END_2

NS_BEGIN_2(odbclib,cursor)

ENUM_BEGIN(CursorType)
	ENUM_ITEM_PAIR(ForwardOnly,SQL_CURSOR_FORWARD_ONLY)
	ENUM_ITEM_PAIR(KeysetDirven,SQL_CURSOR_KEYSET_DRIVEN)
	ENUM_ITEM_PAIR(Dynamic,SQL_CURSOR_DYNAMIC)
	ENUM_ITEM_PAIR(Static,SQL_CURSOR_STATIC)
ENUM_END(CursorType)
ENUM_OUTPUT_DECL(CursorType)

ENUM_BEGIN(CursorScrollable)
	ENUM_ITEM_PAIR(Nonscrollable,SQL_NONSCROLLABLE)
	ENUM_ITEM_PAIR(Scrollable,SQL_SCROLLABLE)
ENUM_END(CursorScrollable)
ENUM_OUTPUT_DECL(CursorScrollable)

ENUM_BEGIN(CursorSensitivity)
	ENUM_ITEM_PAIR(Insensitive,SQL_INSENSITIVE)
	ENUM_ITEM_PAIR(Sensitive,SQL_SENSITIVE)
ENUM_END(CursorSensitivity)
ENUM_OUTPUT_DECL(CursorSensitivity)

ENUM_BEGIN(CursorConcurrency)
	ENUM_ITEM_PAIR(ReadOnly,SQL_CONCUR_READ_ONLY)
	ENUM_ITEM_PAIR(Lock,SQL_CONCUR_LOCK)
	ENUM_ITEM_PAIR(RowVersion,SQL_CONCUR_ROWVER)
	ENUM_ITEM_PAIR(Values,SQL_CONCUR_VALUES)
ENUM_END(CursorConcurrency)
ENUM_OUTPUT_DECL(CursorConcurrency)

ENUM_BEGIN(CursorBehavior)
	ENUM_ITEM_PAIR(Delete,SQL_CB_DELETE)
	ENUM_ITEM_PAIR(Close,SQL_CB_CLOSE)
	ENUM_ITEM_PAIR(Preserve,SQL_CB_PRESERVE)
ENUM_END(CursorBehavior)
ENUM_OUTPUT_DECL(CursorBehavior)

NS_END_2
